### PR TITLE
Don't trigger the exception event handler twice per exception

### LINKED ISSUE #618: Exception events are triggered twice per exception
I noticed that Adhearsion (v3.0.0.rc1) always logs exceptions twice and I was wondering why that is. It seems to be because you're triggering `Adhearsion::Events.trigger :exception` twice, once in `CallController#bg_exec` via `catching_standard_errors` and once in `CallController#execute!`.

### PR DESCRIPTION
**Pull request by chewi**
This resulted in exceptions being logged twice. We don't need to call `catching_standard_errors` in `CallController#bg_exec` because the handler is already triggered in `CallController#execute!`. We do still have to rescue the exceptions though, otherwise they leak out into Celluloid and actually get logged three times!

Fixes #618.

### CODE REVIEW

**Comment by chewi** [comment]
This is the same unrelated failure as my other PR. Again, I hope an updated Nokogiri will help but I'm not sure. I'm close to making that happen though.

**Comment by sfgeorge** [comment]
Awesome, nice work James!!

**Review by sfgeorge — APPROVED** [review]
👍

**Comment by sfgeorge** [comment]
@chewi can you retarget the PR to the develop branch?

**Comment by chewi** [comment]
Done.

**Comment by sfgeorge** [comment]
Sorry for the back and forth - could you also add a line-item for the fix to CHANGELOG.md?  Thanks man.

Last comment from me, I promise!

**Comment by chewi** [comment]
D'oh, why do I always forget that. Done.

**Comment by chewi** [comment]
Travis seems to be rerunning this periodically for some reason. Can we get it merged so it stops?

File: lib/adhearsion/call_controller.rb [hunk 1]
```diff
@@ -108,8 +108,9 @@ def exec(controller = self)
 
     def bg_exec(completion_callback = nil)
       Celluloid::ThreadHandle.new(Celluloid.actor_system) do
-        catching_standard_errors do
+        begin
           exec_with_callback completion_callback
+        rescue StandardError
```
Comment (bklang) [inline lib/adhearsion/call_controller.rb]: Are there any cases where an error would be silently swallowed here? I understand that there's a place deeper in the code which logs it, but are there any ways for an exception to happen outside that catcher/logger?

Comment (chewi) [reply lib/adhearsion/call_controller.rb]: True, it could happen. `exec_with_callback` and `exec` are short and simple but the optional `completion_callback` wouldn't be covered either. Any suggestions?

Comment (bklang) [reply lib/adhearsion/call_controller.rb]: What about removing the deeper exception catcher/logger, and leaving this one in place? Any downside?

Comment (chewi) [reply lib/adhearsion/call_controller.rb]: I guess we'd keep the `on_error` call and the reraise, removing just the trigger. I've checked and `execute!` is not called from elsewhere. It's also marked (but is not really) private so this should be fine. I'll give it a try.

**Comment by chewi** [comment]
Okay, this alternative approach should give better error visibility.

**Review by bklang — APPROVED** [review]
Looks great! Thank you
